version: '3'

services:
  flashback-be-srvc:
    image: flashback-be-srvc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  db:
    image: mongo
    restart: always
    ports:
      
