version: '3'

services:
  backend:
    image: stand87/konomi_be_srvc
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    links:
      - db
  db:
    image: postgres:10.4
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  backend:
  db:
